# Form implementation generated from reading ui file './windows/settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import localization
import Entities
import support

turbo_statuses = Entities.TurboStatuses()

languages = Entities.Languages()
trans = localization.trans

class Ui_Dialog(object):
    def setupUi(self, Dialog, locale):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Dialog.resize(440, 556)
        Dialog.setMinimumSize(QtCore.QSize(440, 556))
        Dialog.setMaximumSize(QtCore.QSize(440, 556))
        Dialog.setToolTip("")
        Dialog.setStyleSheet("background: #fff;")
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(30, 0))
        self.frame.setMaximumSize(QtCore.QSize(30, 16777215))
        self.frame.setStyleSheet("background: #eee; border-right: 1px solid #d8d8d8; border-top: 1px solid #d8d8d8;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setContentsMargins(4, 12, 6, 16)
        self.verticalLayout_10.setSpacing(8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(15, 357, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.buttonSaveSettings = QtWidgets.QPushButton(self.frame)
        self.buttonSaveSettings.setMinimumSize(QtCore.QSize(20, 20))
        self.buttonSaveSettings.setMaximumSize(QtCore.QSize(20, 20))
        self.buttonSaveSettings.setStyleSheet("QPushButton {\n"
"    border:solid 0px;\n"
"    qproperty-icon: url(\" \"); /* empty image */\n"
"    /*qproperty-iconSize: 20px 20px;  space for the background image */\n"
"    border-image: url("+ support.getResourcePath('./images/save.svg')+ ");\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image : url("+ support.getResourcePath('./images/save_hover.svg')+ ");\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    border-image : url("+ support.getResourcePath('./images/save_pressed.svg')+ ");\n"
"    background-repeat: no-repeat;\n"
"}")
        self.buttonSaveSettings.setText("")
        self.buttonSaveSettings.setObjectName("buttonSaveSettings")
        self.verticalLayout_10.addWidget(self.buttonSaveSettings)
        self.verticalLayout_9.addWidget(self.frame)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 6, 12, 12)
        self.verticalLayout_8.setSpacing(8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelNameAndVersion = QtWidgets.QLabel(Dialog)
        self.labelNameAndVersion.setStyleSheet("font-weight: bold; color: #222; font-size:12px;")
        self.labelNameAndVersion.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelNameAndVersion.setObjectName("labelNameAndVersion")
        self.verticalLayout_7.addWidget(self.labelNameAndVersion)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.comboBoxLanguage = QtWidgets.QComboBox(Dialog)
        self.comboBoxLanguage.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBoxLanguage.setStyleSheet("QWidget {\n"
"    border: 1px solid #b6b6b6;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    padding-bottom:2px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QWidget:disabled{\n"
"    border: 1px solid #a9a9a9;\n"
"}\n"
"\n"
"QWidget:drop-down {\n"
"    border-width: 0px;\n"
"}")
        self.comboBoxLanguage.setObjectName("comboBoxLanguage")
        self.horizontalLayout_8.addWidget(self.comboBoxLanguage)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.spinBoxLoggingInterval = QtWidgets.QDoubleSpinBox(Dialog)
        self.spinBoxLoggingInterval.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxLoggingInterval.setSingleStep(0.1)
        self.spinBoxLoggingInterval.setProperty("value", 1.0)
        self.spinBoxLoggingInterval.setObjectName("spinBoxLoggingInterval")
        self.horizontalLayout_2.addWidget(self.spinBoxLoggingInterval)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxStoreStat = QtWidgets.QCheckBox(Dialog)
        self.checkBoxStoreStat.setToolTip("")
        self.checkBoxStoreStat.setToolTipDuration(-1)
        self.checkBoxStoreStat.setWhatsThis("")
        self.checkBoxStoreStat.setChecked(True)
        self.checkBoxStoreStat.setObjectName("checkBoxStoreStat")
        self.verticalLayout_2.addWidget(self.checkBoxStoreStat)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #444;\n"
"margin-left:16px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.checkBoxCloseToTray = QtWidgets.QCheckBox(Dialog)
        self.checkBoxCloseToTray.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.checkBoxCloseToTray.setChecked(False)
        self.checkBoxCloseToTray.setObjectName("checkBoxCloseToTray")
        self.verticalLayout_8.addWidget(self.checkBoxCloseToTray)
        self.checkBoxOpenMinimized = QtWidgets.QCheckBox(Dialog)
        self.checkBoxOpenMinimized.setObjectName("checkBoxOpenMinimized")
        self.verticalLayout_8.addWidget(self.checkBoxOpenMinimized)
        self.checkBoxAutostartIsActive = QtWidgets.QCheckBox(Dialog)
        self.checkBoxAutostartIsActive.setObjectName("checkBoxAutostartIsActive")
        self.verticalLayout_8.addWidget(self.checkBoxAutostartIsActive)
        spacerItem3 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_8.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_17.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_2.setStyleSheet("font-weight: bold; color: #222; font-size:12px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_17.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #444;\n"
"margin-top:4px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_17.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_17)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_5.addItem(spacerItem4)
        self.checkBoxCPUManagment = QtWidgets.QCheckBox(Dialog)
        self.checkBoxCPUManagment.setObjectName("checkBoxCPUManagment")
        self.verticalLayout_5.addWidget(self.checkBoxCPUManagment)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #444;\n"
"margin-left:16px;\n"
"margin-top:2px;")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(16, -1, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCPUThreshhold = QtWidgets.QLabel(Dialog)
        self.labelCPUThreshhold.setEnabled(False)
        self.labelCPUThreshhold.setObjectName("labelCPUThreshhold")
        self.horizontalLayout.addWidget(self.labelCPUThreshhold)
        self.spinBoxCPUThreshhold = QtWidgets.QSpinBox(Dialog)
        self.spinBoxCPUThreshhold.setEnabled(False)
        self.spinBoxCPUThreshhold.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxCPUThreshhold.setMinimum(1)
        self.spinBoxCPUThreshhold.setProperty("value", 50)
        self.spinBoxCPUThreshhold.setObjectName("spinBoxCPUThreshhold")
        self.horizontalLayout.addWidget(self.spinBoxCPUThreshhold)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.labelCPUTreshholdHint = QtWidgets.QLabel(Dialog)
        self.labelCPUTreshholdHint.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.labelCPUTreshholdHint.setFont(font)
        self.labelCPUTreshholdHint.setStyleSheet("QWidget {\n"
"color: #444;\n"
"margin-left:16px;\n"
"margin-top:2px;\n"
"}\n"
"\n"
"QWidget:disabled{color: #999;}")
        self.labelCPUTreshholdHint.setObjectName("labelCPUTreshholdHint")
        self.verticalLayout_4.addWidget(self.labelCPUTreshholdHint)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(16, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelCPUIdleState = QtWidgets.QLabel(Dialog)
        self.labelCPUIdleState.setEnabled(False)
        self.labelCPUIdleState.setObjectName("labelCPUIdleState")
        self.horizontalLayout_3.addWidget(self.labelCPUIdleState)
        self.spinBoxCPUIdleState = QtWidgets.QSpinBox(Dialog)
        self.spinBoxCPUIdleState.setEnabled(False)
        self.spinBoxCPUIdleState.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxCPUIdleState.setMinimum(1)
        self.spinBoxCPUIdleState.setProperty("value", 99)
        self.spinBoxCPUIdleState.setObjectName("spinBoxCPUIdleState")
        self.horizontalLayout_3.addWidget(self.spinBoxCPUIdleState)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(16, 0, -1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelCPULoadState = QtWidgets.QLabel(Dialog)
        self.labelCPULoadState.setEnabled(False)
        self.labelCPULoadState.setObjectName("labelCPULoadState")
        self.horizontalLayout_4.addWidget(self.labelCPULoadState)
        self.spinBoxCPULoadState = QtWidgets.QSpinBox(Dialog)
        self.spinBoxCPULoadState.setEnabled(False)
        self.spinBoxCPULoadState.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxCPULoadState.setMinimum(1)
        self.spinBoxCPULoadState.setMaximum(100)
        self.spinBoxCPULoadState.setProperty("value", 100)
        self.spinBoxCPULoadState.setObjectName("spinBoxCPULoadState")
        self.horizontalLayout_4.addWidget(self.spinBoxCPULoadState)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.labelCPULoadStateHint = QtWidgets.QLabel(Dialog)
        self.labelCPULoadStateHint.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.labelCPULoadStateHint.setFont(font)
        self.labelCPULoadStateHint.setStyleSheet("QWidget {\n"
"color: #444;\n"
"margin-left:16px;\n"
"margin-top:2px;\n"
"}\n"
"\n"
"QWidget:disabled{color: #999;}")
        self.labelCPULoadStateHint.setWordWrap(True)
        self.labelCPULoadStateHint.setObjectName("labelCPULoadStateHint")
        self.verticalLayout_6.addWidget(self.labelCPULoadStateHint)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_8.addItem(spacerItem8)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(16, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBoxCPUTurboManagment = QtWidgets.QCheckBox(Dialog)
        self.checkBoxCPUTurboManagment.setEnabled(False)
        self.checkBoxCPUTurboManagment.setObjectName("checkBoxCPUTurboManagment")
        self.verticalLayout_13.addWidget(self.checkBoxCPUTurboManagment)
        self.labelCPUTurboManagment = QtWidgets.QLabel(Dialog)
        self.labelCPUTurboManagment.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.labelCPUTurboManagment.setFont(font)
        self.labelCPUTurboManagment.setStyleSheet("QWidget {\n"
"color: #444;\n"
"margin-left:16px;\n"
"margin-top:2px;\n"
"}\n"
"\n"
"QWidget:disabled{color: #999;}")
        self.labelCPUTurboManagment.setWordWrap(True)
        self.labelCPUTurboManagment.setObjectName("labelCPUTurboManagment")
        self.verticalLayout_13.addWidget(self.labelCPUTurboManagment)
        self.verticalLayout_16.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(16, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelCPUTurboIdleState = QtWidgets.QLabel(Dialog)
        self.labelCPUTurboIdleState.setEnabled(False)
        self.labelCPUTurboIdleState.setObjectName("labelCPUTurboIdleState")
        self.horizontalLayout_6.addWidget(self.labelCPUTurboIdleState)
        self.comboBoxCPUTurboIdleState = QtWidgets.QComboBox(Dialog)
        self.comboBoxCPUTurboIdleState.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBoxCPUTurboIdleState.sizePolicy().hasHeightForWidth())
        self.comboBoxCPUTurboIdleState.setSizePolicy(sizePolicy)
        self.comboBoxCPUTurboIdleState.setMinimumSize(QtCore.QSize(260, 0))
        self.comboBoxCPUTurboIdleState.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxCPUTurboIdleState.setFont(font)
        self.comboBoxCPUTurboIdleState.setStyleSheet("QWidget {\n"
"    border: 1px solid #b6b6b6;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    padding-bottom:2px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QWidget:disabled{\n"
"    border: 1px solid #a9a9a9;\n"
"}\n"
"\n"
"QWidget:drop-down {\n"
"    border-width: 0px;\n"
"}")
        self.comboBoxCPUTurboIdleState.setIconSize(QtCore.QSize(20, 20))
        self.comboBoxCPUTurboIdleState.setFrame(False)
        self.comboBoxCPUTurboIdleState.setObjectName("comboBoxCPUTurboIdleState")
        self.horizontalLayout_6.addWidget(self.comboBoxCPUTurboIdleState)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.verticalLayout_16.addLayout(self.verticalLayout_12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(16, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelCPUTurboLoadState = QtWidgets.QLabel(Dialog)
        self.labelCPUTurboLoadState.setEnabled(False)
        self.labelCPUTurboLoadState.setObjectName("labelCPUTurboLoadState")
        self.horizontalLayout_7.addWidget(self.labelCPUTurboLoadState)
        self.comboBoxCPUTurboLoadState = QtWidgets.QComboBox(Dialog)
        self.comboBoxCPUTurboLoadState.setEnabled(False)
        self.comboBoxCPUTurboLoadState.setMinimumSize(QtCore.QSize(260, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxCPUTurboLoadState.setFont(font)
        self.comboBoxCPUTurboLoadState.setStyleSheet("QWidget {\n"
"    border: 1px solid #b6b6b6;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    padding-bottom:2px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QWidget:disabled{\n"
"    border: 1px solid #a9a9a9;\n"
"}\n"
"\n"
"QWidget:drop-down {\n"
"    border-width: 0px;\n"
"}")
        self.comboBoxCPUTurboLoadState.setFrame(True)
        self.comboBoxCPUTurboLoadState.setObjectName("comboBoxCPUTurboLoadState")
        self.horizontalLayout_7.addWidget(self.comboBoxCPUTurboLoadState)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.verticalLayout_11.addLayout(self.verticalLayout_16)
        self.verticalLayout_8.addLayout(self.verticalLayout_11)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog, locale)
        self.comboBoxCPUTurboIdleState.setCurrentIndex(-1)
        self.comboBoxCPUTurboLoadState.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, locale):
        Dialog.setWindowTitle(trans(locale, "settings"))
        self.labelNameAndVersion.setText("AveTemp")
        self.label_5.setText(trans(locale, "language"))
        self.label_11.setText(trans(locale, "collection_interval_text"))
        self.checkBoxStoreStat.setText(trans(locale, "collect_and_restore_stat"))
        self.label.setText(trans(locale, "all_data_will_be_removed_when_off"))
        self.checkBoxCloseToTray.setText(trans(locale, "close_to_tray"))
        self.checkBoxOpenMinimized.setText(trans(locale, "start_to_tray"))
        self.checkBoxAutostartIsActive.setText(trans(locale, "add_to_autostart"))
        self.label_2.setText(trans(locale, "cpu_modes_management"))
        self.label_3.setText(trans(locale, "default_when_off"))
        self.checkBoxCPUManagment.setText(trans(locale, "auto_change_cpu_state"))
        self.label_4.setText(trans(locale, "when_load_less_then_then"))
        self.labelCPUThreshhold.setText(trans(locale, "load_threshold"))
        self.labelCPUTreshholdHint.setText(trans(locale, "collect_as_all_cores_load"))
        self.labelCPUIdleState.setText(trans(locale, "idle_state"))
        self.labelCPULoadState.setText(trans(locale, "load_state"))
        self.labelCPULoadStateHint.setText(trans(locale, "state_less_than_100_will"))
        self.checkBoxCPUTurboManagment.setText(trans(locale, "force_cpu_state"))
        self.labelCPUTurboManagment.setText(trans(locale, "auto_change_depends_on_threshold"))
        self.labelCPUTurboIdleState.setText(trans(locale, "in_idle"))
        self.comboBoxCPUTurboIdleState.addItem(trans(locale, turbo_statuses.getEco()['name']), turbo_statuses.getEco()['id'])
        self.comboBoxCPUTurboIdleState.addItem(trans(locale, turbo_statuses.getBasic()['name']), turbo_statuses.getBasic()['id'])
        self.labelCPUTurboLoadState.setText(trans(locale, "on_load"))
        self.comboBoxCPUTurboLoadState.addItem(trans(locale, turbo_statuses.getBasic()['name']), turbo_statuses.getBasic()['id'])
        self.comboBoxCPUTurboLoadState.addItem(trans(locale, turbo_statuses.getTurbo()['name']), turbo_statuses.getTurbo()['id'])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, "en")
    Dialog.show()
    sys.exit(app.exec())
