# Form implementation generated from reading ui file './windows/settings.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Dialog.resize(342, 206)
        Dialog.setToolTip("")
        Dialog.setStyleSheet("background: #fff;")
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNameAndVersion = QtWidgets.QLabel(Dialog)
        self.labelNameAndVersion.setStyleSheet("font-weight: bold; color: #222; font-size:12px;")
        self.labelNameAndVersion.setText("")
        self.labelNameAndVersion.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelNameAndVersion.setObjectName("labelNameAndVersion")
        self.verticalLayout.addWidget(self.labelNameAndVersion)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.spinBoxLoggingInterval = QtWidgets.QDoubleSpinBox(Dialog)
        self.spinBoxLoggingInterval.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxLoggingInterval.setSingleStep(0.1)
        self.spinBoxLoggingInterval.setProperty("value", 1.0)
        self.spinBoxLoggingInterval.setObjectName("spinBoxLoggingInterval")
        self.horizontalLayout_2.addWidget(self.spinBoxLoggingInterval)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxStoreStat = QtWidgets.QCheckBox(Dialog)
        self.checkBoxStoreStat.setToolTip("")
        self.checkBoxStoreStat.setToolTipDuration(-1)
        self.checkBoxStoreStat.setWhatsThis("")
        self.checkBoxStoreStat.setChecked(True)
        self.checkBoxStoreStat.setObjectName("checkBoxStoreStat")
        self.verticalLayout_2.addWidget(self.checkBoxStoreStat)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #444;\n"
"margin-left:16px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.checkBoxCloseToTray = QtWidgets.QCheckBox(Dialog)
        self.checkBoxCloseToTray.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.checkBoxCloseToTray.setChecked(False)
        self.checkBoxCloseToTray.setObjectName("checkBoxCloseToTray")
        self.verticalLayout.addWidget(self.checkBoxCloseToTray)
        self.checkBoxOpenMinimized = QtWidgets.QCheckBox(Dialog)
        self.checkBoxOpenMinimized.setObjectName("checkBoxOpenMinimized")
        self.verticalLayout.addWidget(self.checkBoxOpenMinimized)
        self.buttonSaveSettings = QtWidgets.QPushButton(Dialog)
        self.buttonSaveSettings.setStyleSheet("QPushButton {\n"
"    border-radius:4px; \n"
"    background: #e1e1e1; \n"
"    padding: 4px; \n"
"    font-weight: bold; \n"
"    color: #222;\n"
"    border: 1px solid #d8d8d8;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   background: #d8d8d8; \n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"   background: #c9c9c9; \n"
"}")
        self.buttonSaveSettings.setObjectName("buttonSaveSettings")
        self.verticalLayout.addWidget(self.buttonSaveSettings)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки"))
        self.label_11.setText(_translate("Dialog", "Интервал сбора, секунды: "))
        self.checkBoxStoreStat.setText(_translate("Dialog", "Хранить и восстанавливать статистику за сутки"))
        self.label.setText(_translate("Dialog", "При отключении все собранные данные будут удалены"))
        self.checkBoxCloseToTray.setText(_translate("Dialog", "При закрытии сворачивать в трей"))
        self.checkBoxOpenMinimized.setText(_translate("Dialog", "Запускать свернутым"))
        self.buttonSaveSettings.setText(_translate("Dialog", "Применить"))
